export const blogCategories = [
  'Frontend',
  'Backend',
  'Full Stack',
  'DevOps',
  'Database',
  'Authentication',
  'Tutorial',
  'Career',
  'Case Study',
] as const;

export const blogTags = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Node.js',
  'Express.js',
  'MongoDB',
  'Mongoose',
  'Prisma',
  'REST API',
  'Authentication',
  'JWT',
  'Better Auth',
  'OAuth',
  'Google Login',
  'Docker',
  'Vercel',
  'Git',
  'GitHub',
  'Tailwind CSS',
  'shadcn/ui',
  'Redux',
  'TanStack Query',
  'React Hook Form',
  'Zod',
  'Performance',
  'SEO',
  'Bug Fixing',
  'Deployment',
  'Project Setup',
  'Clean Code',
  'System Design',
] as const;
