import { SkillCategoryDTO } from '@/src/types/skill.interface'

export const SKILL_CATEGORIES: SkillCategoryDTO[] = [
	{
		id: 'languages',
		label: 'Languages',
		iconName: 'Code2',
		slug: 'languages',
		order: 0,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'frontend',
		label: 'Frontend',
		iconName: 'Palette',
		slug: 'frontend',
		order: 1,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'styling-ui',
		label: 'Styling & UI',
		iconName: 'Paintbrush',
		slug: 'styling-ui',
		order: 2,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'backend',
		label: 'Backend',
		iconName: 'Server',
		slug: 'backend',
		order: 3,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'database',
		label: 'Database',
		iconName: 'Database',
		slug: 'database',
		order: 4,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'tools-devops',
		label: 'Tools & DevOps',
		iconName: 'Wrench',
		slug: 'tools-devops',
		order: 5,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'payment-validation',
		label: 'Payment & Validation',
		iconName: 'CreditCard',
		slug: 'payment-validation',
		order: 6,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
]
